## CHAPTER 3 텐서플로 프로그래밍  101


### 3.1 텐서와 그래프 실행

In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant('Hello, Tensorflow!')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
3 # 랭크가 0인 텐서; 셰이프는 []
[1. ,2., 3.] # 랭크가 1인 텐서; 셰이프는 [3]
[[1., 2., 3.], [4., 5., 6.]] # 랭크가 2인 텐서; 셰이프는[2, 3]
[[[1., 2., 3.]], [[7., 8., 9.]]] # 랭크가 3인 텐서; 셰이프는 [2, 1, 3]

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

In [4]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [5]:
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a, b, c]))

sess.close()

b'Hello, Tensorflow!'
[10, 32, 42]


### 3.2 플레이스홀더와 변수

In [6]:
#None은 크기가 정해지지 않았음을 의미합니다.
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [7]:
x_data = [[1, 2, 3], [4, 5, 6]]

In [8]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

In [9]:
W = tf.Variable([[0.1, 0.1], [0.2, 0.2], [0.3, 0.3]])

In [10]:
expr = tf.matmul(X, W) + b

In [11]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[0.1 0.1]
 [0.2 0.2]
 [0.3 0.3]]
=== b ===
[[-0.44998747]
 [ 0.09067396]]
=== expr ===
[[0.9500126 0.9500126]
 [3.290674  3.290674 ]]


### 3.3 선형 회귀 모델 구현하기

In [12]:
x_data = [1, 2, 3]
y_data = [1, 2, 3]

In [13]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

In [14]:
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

In [15]:
hypothesis = W * X + b

In [16]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [17]:
optimzer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimzer.minimize(cost)

In [18]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data,
                                                            Y: y_data})
    
        print(step, cost_val, sess.run(W), sess.run(b))
        
        print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
        print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))

0 4.085737 [0.78189296] [0.7267197]
X: 5, Y: [4.6361847]
X: 2.5, Y: [2.681452]
1 0.11610729 [0.69477165] [0.66861856]
X: 5, Y: [4.142477]
X: 2.5, Y: [2.4055476]
2 0.06549236 [0.71220404] [0.6569862]
X: 5, Y: [4.218006]
X: 2.5, Y: [2.4374962]
3 0.06184268 [0.7180191] [0.6407073]
X: 5, Y: [4.230803]
X: 2.5, Y: [2.435755]
4 0.05889869 [0.72491837] [0.6253582]
X: 5, Y: [4.24995]
X: 2.5, Y: [2.437654]
5 0.056100894 [0.731518] [0.61031926]
X: 5, Y: [4.267909]
X: 2.5, Y: [2.439114]
6 0.05343606 [0.7379735] [0.5956482]
X: 5, Y: [4.285516]
X: 2.5, Y: [2.440582]
7 0.05089778 [0.74427223] [0.58132917]
X: 5, Y: [4.3026905]
X: 2.5, Y: [2.4420097]
8 0.04848011 [0.75041986] [0.56735444]
X: 5, Y: [4.3194537]
X: 2.5, Y: [2.4434042]
9 0.04617728 [0.75641954] [0.5537156]
X: 5, Y: [4.3358135]
X: 2.5, Y: [2.4447646]
10 0.043983813 [0.7622751] [0.5404047]
X: 5, Y: [4.3517804]
X: 2.5, Y: [2.4460926]
11 0.04189455 [0.7679898] [0.5274137]
X: 5, Y: [4.367363]
X: 2.5, Y: [2.4473882]
12 0.039904516 [0.77356714] [